# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(null=True, verbose_name='N')),
                ('t', models.DateTimeField(null=True, verbose_name='T')),
                ('x', models.FloatField(null=True, verbose_name='X')),
                ('y', models.FloatField(null=True, verbose_name='Y')),
                ('z', models.FloatField(null=True, verbose_name='Z')),
                ('s', models.FloatField(null=True, verbose_name='S')),
                ('m', models.IntegerField(null=True, verbose_name='M')),
                ('ball_posession', models.IntegerField(null=True, verbose_name='BallPossession')),
                ('ball_status', models.IntegerField(null=True, verbose_name='BallStatus')),
            ],
            options={
                'verbose_name': 'Frame',
                'verbose_name_plural': 'Frames',
            },
        ),
        migrations.CreateModel(
            name='FrameSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_section', models.CharField(max_length=20, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Match')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.MatchPlayer')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.MatchTeam')),
            ],
            options={
                'verbose_name': 'FrameSet',
                'verbose_name_plural': 'FrameSets',
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posdata.FrameSet', verbose_name='FrameSet'),
        ),
    ]
