# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-11 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='ball_posession',
            new_name='ball_possession',
        ),
    ]
