# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posdata', '0002_auto_20170811_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='n',
            field=models.IntegerField(db_index=True, null=True, verbose_name='N'),
        ),
    ]
