# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='MatchId')),
                ('competition', models.CharField(max_length=50, null=True, verbose_name='Competition')),
                ('competition_id', models.CharField(max_length=50, null=True, verbose_name='CompetitionId')),
                ('dl_provider_id', models.CharField(max_length=50, null=True, verbose_name='DL-PROVIDER-ID')),
                ('game_title', models.CharField(max_length=200, null=True, verbose_name='GameTitle')),
                ('host', models.CharField(max_length=200, null=True, verbose_name='Host')),
                ('kickoff_time', models.DateTimeField(null=True, verbose_name='KickoffTime')),
                ('planned_kickoff_time', models.DateTimeField(null=True, verbose_name='PlannedKickoffTime')),
                ('match_day', models.IntegerField(null=True, verbose_name='MatchDay')),
                ('season', models.CharField(max_length=50, null=True, verbose_name='Season')),
                ('match_type', models.CharField(max_length=50, null=True, verbose_name='Type')),
                ('sport_type', models.CharField(max_length=50, null=True, verbose_name='TypeOfSport')),
                ('playing_time_first_half', models.IntegerField(blank=True, null=True, verbose_name='PlayingTimeFirstHalf')),
                ('playing_time_second_half', models.IntegerField(blank=True, null=True, verbose_name='PlayingTimeSecondHalf')),
                ('total_time_first_half', models.IntegerField(blank=True, null=True, verbose_name='TotalTimeFirstHalf')),
                ('total_time_second_half', models.IntegerField(blank=True, null=True, verbose_name='TotalTimeSecondHalf')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playing_position', models.CharField(max_length=5, null=True, verbose_name='PlayingPosition')),
                ('team_leader', models.NullBooleanField(verbose_name='TeamLeader')),
                ('shirt_number', models.IntegerField(null=True, verbose_name='ShirtNumber')),
                ('starting', models.NullBooleanField(verbose_name='Starting')),
            ],
        ),
        migrations.CreateModel(
            name='MatchStadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floodlight', models.CharField(max_length=20, null=True, verbose_name='Floodlight')),
                ('pitch_erosion', models.CharField(max_length=50, null=True, verbose_name='PitchErosion')),
                ('precipitation', models.CharField(max_length=50, null=True, verbose_name='Precipitation')),
                ('roof', models.CharField(max_length=20, null=True, verbose_name='Roof')),
                ('soldout', models.NullBooleanField(verbose_name='SoldOut')),
                ('temperature', models.IntegerField(null=True, verbose_name='Temperature')),
                ('number_of_spectators', models.IntegerField(null=True, verbose_name='NumberOfSpectators')),
                ('air_humidity', models.IntegerField(null=True, verbose_name='AirHumidity')),
                ('air_pressure', models.IntegerField(null=True, verbose_name='AirPressure')),
                ('match', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(max_length=7, null=True, verbose_name='PlayerMainColorOfShirt')),
                ('other_color', models.CharField(max_length=7, null=True, verbose_name='PlayerOtherColorOfShirt')),
                ('role', models.CharField(max_length=6, null=True, verbose_name='Role')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='PersonId')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='LastName')),
                ('short_name', models.CharField(max_length=50, null=True, verbose_name='Shortname')),
                ('role', models.CharField(max_length=50, null=True, verbose_name='Role')),
                ('job', models.CharField(max_length=50, null=True)),
                ('match_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.MatchTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='PersonId')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='LastName')),
                ('short_name', models.CharField(max_length=50, null=True, verbose_name='Shortname')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('person_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='PersonId')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='LastName')),
                ('short_name', models.CharField(max_length=50, null=True, verbose_name='Shortname')),
                ('role', models.CharField(max_length=50, null=True, verbose_name='Role')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='StadiumId')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='StadiumName')),
                ('capacity', models.IntegerField(null=True, verbose_name='StadiumCapacity')),
                ('pitch_x', models.FloatField(null=True, verbose_name='PitchX')),
                ('pitch_y', models.FloatField(null=True, verbose_name='PitchY')),
                ('adress', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='TeamId')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='TeamName')),
            ],
        ),
        migrations.AddField(
            model_name='matchteam',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Team'),
        ),
        migrations.AddField(
            model_name='matchstadium',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Stadium'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='match_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.MatchTeam'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='matchteam',
            unique_together=set([('team', 'match')]),
        ),
        migrations.AlterUniqueTogether(
            name='matchstadium',
            unique_together=set([('stadium', 'match')]),
        ),
    ]
